### ISSUE TITLE
HealthCheckTest#databaseConnectivityFailure causes Service shutdown failures

### ISSUE THREAD

**Issue by jmuia** [square/misk#264]
Test performs correctly, but closing the SessionFactory means that any code that runs after the test and relies on the SessionFactory will fail (eg. TruncateTablesService shutdown statements). It would be good to use another method to fake a database failure.

**Comment by swankjesse** [comment]
I’m seeing test failures in CI:
```
Jun 20, 2018 11:22:00 AM com.google.common.util.concurrent.ServiceManager$ServiceListener failed
SEVERE: Service TruncateTablesService [FAILED] has failed in the STOPPING state.
java.lang.IllegalStateException: EntityManagerFactory is closed
	at org.hibernate.internal.SessionFactoryImpl.validateNotClosed(SessionFactoryImpl.java:531)
	at org.hibernate.internal.SessionFactoryImpl.getCache(SessionFactoryImpl.java:830)
	at org.hibernate.internal.AbstractSharedSessionContract.<init>(AbstractSharedSessionContract.java:145)
	at org.hibernate.internal.AbstractSessionImpl.<init>(AbstractSessionImpl.java:29)
	at org.hibernate.internal.SessionImpl.<init>(SessionImpl.java:254)
	at org.hibernate.internal.SessionFactoryImpl$SessionBuilderImpl.openSession(SessionFactoryImpl.java:1290)
	at org.hibernate.internal.SessionFactoryImpl.openSession(SessionFactoryImpl.java:482)
	at misk.hibernate.TruncateTablesService.executeStatements(TruncateTablesService.kt:92)
	at misk.hibernate.TruncateTablesService.shutDown(TruncateTablesService.kt:46)
	at com.google.common.util.concurrent.AbstractIdleService$DelegateService$2.run(AbstractIdleService.java:79)
	at com.google.common.util.concurrent.Callables$4.run(Callables.java:119)
	at java.lang.Thread.run(Thread.java:748)
```
